Update unit test CI workflow

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -29,6 +29,17 @@ jobs:
       # TODO: Add the script for the unit tests here
       - name: Unit tests
         run: |
-          #!/bin/sh
+          #!/bin/bash
           . ./venv/bin/activate
-          pytest src/beeflow/tests/test_*.py
+          . ./ci/env.sh
+          set +e
+          code=0
+          for test in src/beeflow/tests/test_*.py; do
+              pytest $test
+              result=$?
+              # Ensure the step fails if one test fails
+              if [ $result -ne 0 ]; then
+                  code=$result
+              fi
+          done
+          exit $code
